### ISSUE TITLE
Issue with paths

### ISSUE THREAD

**Issue by ghost** [Parkmck/Dungeon-Of-Droobaxe#1]
Hi,
Python cannot access resources (images) . This seems to be due to the backslashs ("\\") in the paths: the error disappears when I replace them with simple slashes ("/").

Thank you in advance for your answer.

**Comment by Parkmck** [comment]
I am not sure why but on my end I am not seeing the same thing it works fine for me.

**Comment by ghost** [comment]
The error may be due to my os (Ubuntu 18.04)......
But if regular slashes are better supported on different os, perhaps you should replace the backslashs in the source?

**Comment by Parkmck** [comment]
Thank you for pointing that out. In the next update all the back slashes will be replaced with foreword slashes. Please let me know of any other issues on that come up. Thanks!

**Comment by Parkmck** [comment]
All Fixed.
